server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/aavartix_ledger
    username: aavartix_admin
    password: root
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update   # Automatically creates/updates database tables
    show-sql: true       # Prints SQL queries in the console
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  data:
    redis:
      host: localhost
      port: 6379